require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'clevertapBugRepro' do
  config = use_native_modules!
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', :modular_headers => true
  pod 'CleverTap-iOS-SDK', modular_headers: true
  # pod 'CleverTap-iOS-SDK', '3.9.2'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'clevertapBugReproTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
